const actionTypes = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGOUT: "LOGOUT",
  GET_POSTS: "GET_POSTS",
  GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_PRICES: " GET_PRICES",
  GET_AREAS: "GET_AREAS",
  GET_NEW_POSTS: "GET_NEW_POSTS",
  GET_PROVINCES: "GET_PROVINCES",
};
export default actionTypes;
